version: '3.8'

services:
  dev:
    build: .
    container_name: ku-konnect
    networks:
      - traefik_default
    volumes:
      - .:/home/coder/project
    environment:
      - PASSWORD=next!konnect
      - PROXY_DOMAIN=konnect-dev.hydv.kr
    restart: always
    command: ["--auth", "password", "--bind-addr", "0.0.0.0:8080", "."]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ku-konnect-code.rule=Host(`konnect-dev.hydv.kr`)"
      - "traefik.http.routers.ku-konnect-code.service=konnect-srv-code"
      - "traefik.http.routers.ku-konnect-code.entrypoints=websecure"
      - "traefik.http.routers.ku-konnect-code.tls=true"
      - "traefik.http.routers.ku-konnect-code.tls.certresolver=myresolver"
      - "traefik.http.services.konnect-srv-code.loadbalancer.server.port=8080"
      - "traefik.http.routers.ku-konnect-front.rule=Host(`konnect.hydv.kr`)"
      - "traefik.http.routers.ku-konnect-front.service=konnect-srv-front"
      - "traefik.http.services.konnect-srv-front.loadbalancer.server.port=5173"
      - "traefik.http.routers.ku-konnect-back.rule=Host(`konnect-api.hydv.kr`)"
      - "traefik.http.routers.ku-konnect-back.service=konnect-srv-back"
      - "traefik.http.services.konnect-srv-back.loadbalancer.server.port=3000"

networks:
  traefik_default:
    external: true