@base = https://api.konnect.hydv.kr

###

POST {{base}}/auth/signup
Content-Type: application/json

{
    "a": 1
}

###

POST {{base}}/auth/signup/cert/get
Content-Type: application/json

{
    "univ_mal": "hello@world.com"
}

###

POST {{base}}/auth